version: 2.1

workflows:
  version: 2
  ci:
    jobs:
      - build
      - test-influxdb:
          matrix:
            parameters:
              version: ["2.0", "2.1"]

jobs:
  build:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - setup_remote_docker
      - run: bash circle-test.sh

  test-influxdb:
    machine:
      image: ubuntu-2004:202201-01
    parameters:
      version:
        type: string
        enum: ["2.0", "2.1"]
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y jq
      - run: bash influxdb/test/test-2x-e2e.sh << parameters.version >>
      - store_artifacts:
          path: influxdb/test/logs
          destination: container-logs
